export const COMPLAINCE_DRAWER_DATA = "COMPLAINCE_DRAWER_DATA"
export const COMPLAINCE_DRAWER_JSON_DATA = "COMPLAINCE_DRAWER_JSON_DATA"
export const COMPLAINCE_DRAWER_REGULATION_DATA = "COMPLAINCE_DRAWER_REGULATION_DATA"
export const COMPLAINCE_DRAWER_REGULATION_MAP = "COMPLAINCE_DRAWER_REGULATION_MAP"
