export const TABLE_ACTIVE_ENDPOINT = "TABLE_ACTIVE_ENDPOINT";
export const TABLE_CONTENTS = "TABLE_CONTENTS";
export const FILTERED_TABLE_CONTENTS = "FILTERED_TABLE_CONTENTS";
export const TABLE_TABS = "TABLE_TABS";
